[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = ["https://crystalstocks.netlify.app", "https://crystalstocks-backend.herokuapp.com"]